name: Push to EC2

on: push

jobs:
  push:
    runs-on: ubuntu-latest
    permissions: write-all

    steps:
      - name: Checkout the file
        uses: actions/checkout@v2

      - name: Deploy to EC2
        uses: easingthemes/ssh-deploy@main
        env:
          SSH_PRIVATE_KEY: ${{secrets.EC2_PEM }}
          REMOTE_HOST: "ec2-13-49-64-25.eu-north-1.compute.amazonaws.com"
          SOURCE: "./"
          REMOTE_USER: "ubuntu"
          TARGET: "/var/www/html"

      #- name: Restart Apache
       # uses: appleboy/ssh-action@master
        #with:
         # host: ${{ secrets.HOST_IP }}
          #username: "ubuntu"
          #key: ${{ secrets.EC2_KEY }}
          #port: 22
          #script: |
            #echo "${{ secrets.SSL_PASSWORD }}" | sudo apachectl restart
